---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-devai168-oct16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-devai168-oct16 
  name: test-devai168-oct16
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi